#!/bin/sh

set -e

load_aesd_char() {
    module="aesdchar"
    device="aesdchar"
    mode="664"

    if grep -q '^staff:' /etc/group; then
        group="staff"
    else
        group="wheel"
    fi

    insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1

    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

    rm -f /dev/${device}
    mknod /dev/${device} c $major 0
    chgrp $group /dev/${device}
    chmod $mode  /dev/${device}
}

unload_aesd_char() {
    module="aesdchar"
    device="aesdchar"

    rmmod $module || exit 1

    rm -f /dev/${device} /dev/${device}
}

case "$1" in
  start)
     echo -n "Loading aesdchar module"
     load_aesd_char
     echo "."
     ;;
  stop)
     echo -n "Unloading aesdchar module"
     unload_aesd_char
     echo "."
     ;;
  force-reload|restart)
     echo -n "Reloading aesdchar module"
     unload_aesd_char
     load_aesd_char
     echo "."
     ;;
  *)
     echo "Usage: $0 {start|stop|restart|force-reload}"
     exit 1
esac

exit 0
