#!/bin/sh

set -e

load_scull() {
    module="scull"
    device="scull"
    mode="664"

    if grep -q '^staff:' /etc/group; then
        group="staff"
    else
        group="wheel"
    fi

    insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1

    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

    rm -f /dev/${device}[0-3]
    mknod /dev/${device}0 c $major 0
    mknod /dev/${device}1 c $major 1
    mknod /dev/${device}2 c $major 2
    mknod /dev/${device}3 c $major 3
    ln -sf ${device}0 /dev/${device}
    chgrp $group /dev/${device}[0-3]
    chmod $mode  /dev/${device}[0-3]

    rm -f /dev/${device}pipe[0-3]
    mknod /dev/${device}pipe0 c $major 4
    mknod /dev/${device}pipe1 c $major 5
    mknod /dev/${device}pipe2 c $major 6
    mknod /dev/${device}pipe3 c $major 7
    ln -sf ${device}pipe0 /dev/${device}pipe
    chgrp $group /dev/${device}pipe[0-3]
    chmod $mode  /dev/${device}pipe[0-3]

    rm -f /dev/${device}single
    mknod /dev/${device}single  c $major 8
    chgrp $group /dev/${device}single
    chmod $mode  /dev/${device}single

    rm -f /dev/${device}uid
    mknod /dev/${device}uid   c $major 9
    chgrp $group /dev/${device}uid
    chmod $mode  /dev/${device}uid

    rm -f /dev/${device}wuid
    mknod /dev/${device}wuid  c $major 10
    chgrp $group /dev/${device}wuid
    chmod $mode  /dev/${device}wuid

    rm -f /dev/${device}priv
    mknod /dev/${device}priv  c $major 11
    chgrp $group /dev/${device}priv
    chmod $mode  /dev/${device}priv
}

unload_scull() {
    module="scull"
    device="scull"

    rmmod $module || exit 1

    rm -f /dev/${device} /dev/${device}[0-3]
    rm -f /dev/${device}priv
    rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
    rm -f /dev/${device}single
    rm -f /dev/${device}uid
    rm -f /dev/${device}wuid
}

load_faulty() {
    module="faulty"
    device="faulty"
    mode="664"

    if grep -q '^staff:' /etc/group; then
        group="staff"
    else
        group="wheel"
    fi

    echo "Load our module, exit on failure"
    insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1

    echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    if [ ! -z ${major} ]; then
        echo "Remove any existing /dev node for /dev/${device}"
        rm -f /dev/${device}
        echo "Add a node for our device at /dev/${device} using mknod"
        mknod /dev/${device} c $major 0
        echo "Change group owner to ${group}"
        chgrp $group /dev/${device}
        echo "Change access mode to ${mode}"
        chmod $mode  /dev/${device}
    else
        echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
    fi
}


unload_faulty() {
    module="faulty"
    device="faulty"

    rmmod $module || exit 1
    rm -f /dev/${device}
}

load_hello() {
    module="hello"

    echo "Load our module, exit on failure"
    insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1
}

unload_hello() {
    module="hello"

    rmmod $module || exit 1
}

case "$1" in
  start)
     echo -n "Loading modules"
     load_scull
     load_faulty
     load_hello
     echo "."
     ;;
  stop)
     echo -n "Unloading modules"
     unload_scull
     unload_faulty
     unload_hello
     echo "."
     ;;
  force-reload|restart)
     echo -n "Reloading modules"
     unload_hello
     unload_faulty
     unload_scull
     load_scull
     load_faulty
     load_hello
     echo "."
     ;;
  *)
     echo "Usage: $0 {start|stop|restart|force-reload}"
     exit 1
esac

exit 0
